### ISSUE TITLE
add wiki for howtos/interactions and put in readme

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#10]

**Comment by mpipoly** [comment]
Comment

**Comment by GHarmata** [comment]
I'm here!

**Comment by tien-tong** [comment]
I'm Tien.

**Comment by jdkent** [comment]
this is done! see the [README](https://github.com/brainhack-uiowa/2019-brainhack/blob/21ea4ee7afafc282529317c737fec1d4738bab92/README.md) and the [wiki](https://github.com/brainhack-uiowa/2019-brainhack/wiki)
