### ISSUE TITLE
scribe for meetings?

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#12]
@TrevorLeeCline would you be able to take notes for the Friday meeting? That way it will be easier to translate our conversation into relevant points in the github issues.

**Comment by TrevorLeeCline** [comment]
Sounds good, James! Just make sure, at least at first, to be clear about
the things that will need to be written down.

I tend to prefer hand notes, but is this something you'd like to be typed?

**Comment by jdkent** [comment]
hand written is fine, but after the meeting they will be translated to a computerized form.
