### ISSUE TITLE
Send Reminder emails for event

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#14]
2 weeks out
1 week out
few days before

**Comment by jdkent** [comment]
send outlook invite

(may be able to automatically send emails)

**Comment by jdkent** [comment]
contents: include mention to bring data and give links to example data.

**Comment by mpipoly** [comment]
Hey All:

what do you think of the below?

Hello UIowa Brainhakers,

You are receiving this message as a reminder that you RSVP'D to our Uiowa Hackathon July 23rd-24th 8:30am-5pm. 

As a reminder, we ask that you bring data to work with or identify open access/free downloadable data to use during the Hackathon event!

Here are some links for the kinds of datasets you might consider employing:

https://openneuro.org/
There is Midnight Scan Club data and NARPS data for neuroimagers (among others)

https://www.nwb.org/allen-cell-types-database/
http://crcns.org/NWB/Data_sets

There are two links above for various electrophysiological data housed along with behavior for folks to play with using the above links.  

We ask that you continue to follow our updates as the Hackathon approaches via our slack page. If you are not already signed up, please email james-kent@uiowa.edu for an invite! 

We look forward to seeing all of you there!

Best,

UIowa Brain Hackathon Committee 2019

Contact Email:
marco-pipoly@uiowa.edu
james-kent@uiowa.edu
gail-harmatte@uiowa.edu

**Comment by GHarmata** [comment]
I think it is pretty good!  There are a few typos, but I think it gets the message across. I would also consider making a bullet-pointed list of the dataset links and descriptions, for clearer organization.  

 > Here are some links for the kinds of datasets you might consider employing:
 > - Midnight Scan Club data and NARPS data for neuroimagers (among others)
 >      - https://openneuro.org/
 > - Various electrophysiological data housed along with behavior
 >      - https://www.nwb.org/allen-cell-types-database/
 >      - http://crcns.org/NWB/Data_sets


Also, did we ask them to bring data/ideas yet, or is this the first time?  We asked faculty, but I can't remember about asking the other participants.

Typos: "Brainhackers", "gail-harmata@uiowa.edu"

**Comment by jdkent** [comment]
Thanks Marco!

- I would replace the word hackathon with brainhack, the [uiowa hackathon](https://hack.uiowa.edu/) is a separate event that has already laid claim to the name.

- We can also link the [google dataset search link](https://toolbox.google.com/datasetsearch), which will help you find datasets. (I've only used it for a couple searches, but it is already scary good).

> We ask that you continue to follow our updates as the Hackathon approaches via our slack page. If you are not already signed up, please email james-kent@uiowa.edu for an invite!

you can use this invite link for the slack group (expires in 30 days): https://join.slack.com/t/2019uibrainhack/shared_invite/enQtNjkxNDcxNjYzMzAyLTIxZTgyZjI2YjkxZWFkOGZhMWQwMmNjZjgwYjVlMzdmMWIwYTkzNTkyNjMwYmUyMTE4YmE1NWNkZmIyZjI2ZmE

I would suggest making it a [hyperlink](https://join.slack.com/t/2019uibrainhack/shared_invite/enQtNjkxNDcxNjYzMzAyLTIxZTgyZjI2YjkxZWFkOGZhMWQwMmNjZjgwYjVlMzdmMWIwYTkzNTkyNjMwYmUyMTE4YmE1NWNkZmIyZjI2ZmE) instead of making them look at the url monstrosity

**Comment by jdkent** [comment]
> As a reminder, we ask that you bring data to work with or identify open access/free downloadable data to use during the Hackathon event!

Another thought is that everyone will not be bringing their own data/project, some (most?) will be bringing their skills and knowledge, so my suggestion would be to make this more optional.

JK
>> If you have a project in mind, we ask that you bring relevant data/documents to work with or identify open access/free downloadable data to use during the brainhack!

**Comment by jdkent** [comment]
and finally(?), could you add Trevor's (trevor-cline@uiowa.edu) and Han's (hans-johnson@uiowa.edu) email to the contact list for the committee?

**Comment by jdkent** [comment]
@mpipoly remember to add the new people that signed up to the reminder email!

**Comment by jdkent** [comment]
Last reminder sent
