### ISSUE TITLE
Create Banner for event?

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#18]
While reading the [brainhack tips](https://www.brainhack.org/host.html), we may want to think about making a banner for the brainhack. Everyone that participated can leave their signature and we can take a picture together at the end.

**Comment by mpipoly** [comment]
I think this sounds like a great idea! Is this something the university or INI can provide?

**Comment by jdkent** [comment]
Could not get this done in time.
