### ISSUE TITLE
photography at the event

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#19]
We should take pictures at the event (at the very least the committee, but we should get everyone participating in the picture).

And ideally we will have pictures throughout the event

**Comment by mpipoly** [comment]
This sounds great!

**Comment by jdkent** [comment]
I'll see if Lex would want to do this.

**Comment by jdkent** [comment]
Lex said she is up for this, I asked her to come on the 23rd.
