### ISSUE TITLE
Funding Sources

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#2]
INI (contacted Meghan Lawler; waiting to hear back)
something from the INCF?
any support from computational psychiatry?

**Comment by jdkent** [comment]
INI said they would fund ~10 people for the event.

**Comment by jdkent** [comment]
DELTA and computational psychiatry, may have interest in UK biobank and HCP

**Comment by mpipoly** [comment]
This sounds great. I have been fussing with HCP data a lot recently, including their Workbench command line functions. I am unfamiliar with UK biobank. Is this something we will need to acquire in say a "docker" type environment?

**Comment by jdkent** [comment]
whoops, sorry this question slipped through the cracks. UK biobank is analogous to HCP in the sense someone else "owns" the data and we have go through paperwork/electronicwork(?) to obtain access. 

docker is a separate concept can be helpful once you have the data and want to analyze it in a way you could reproduce. So if someone else gets the data, they can use your docker container and get the same results you did.

**Comment by jdkent** [comment]
INI provided sufficient funding
