### ISSUE TITLE
Add attendance sheet

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#21]
use a sign up to keep track the people.

**Comment by jdkent** [comment]
@GHarmata could you make/print a sign-in/sign-up sheet? I think columns for first name, last name, department (or affiliation), and position (e.g. graduate student, post-doc, assistant professor, etc.) would be excellent.

**Comment by GHarmata** [comment]
[UI Brainhack 2019 Sign up.docx](https://github.com/brainhack-uiowa/2019-brainhack/files/3407667/UI.Brainhack.2019.Sign.up.docx)

**Comment by jdkent** [comment]
printed and used.
