### ISSUE TITLE
Invite ignite speakers

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#3]
Have faculty talk about  problems/ideas to solve/work on while at the hackathon or provide general inspiration for people.

## Potential contacts

- Dan Thedans
- Tim Koscik
- Vince Magnotta
- Hans Johnson
- Michelle Voss
- Aaron Boes
- Jan Wessel
- Jake Michaelson
- Kai Hwang
- Joel Bruss
- Chris Kovach

**Comment by jdkent** [comment]
we will have 2 bursts of talks.

**Comment by jdkent** [comment]
Update, we have about 12 people signing up, with some faculty sign-ups, so it may be the case we ask the faculty that have signed up to give a short presentation on what they would like to work on... thoughts?

**Comment by mpipoly** [comment]
jdkent - I think that is an excellent idea. With what we have seen so far, do you think this will be enough in terms of speakers for each burst of talks?

**Comment by jdkent** [comment]
Given the make-up of the participants that have signed up (a few are faculty), the ignite talks may just be scraped and absorbed by project pitches (with emails being sent to the faculty to make one). To accomplish this, the project pitches may be given more time 3-10 minutes to give sufficient background to get participants excited.

This will be another item on the agenda.

**Comment by jdkent** [comment]
Tien will no longer be able to contact individuals for project pitches. I still want a few more people to give project pitches (so we will need to email some potential interested faculty to get the ball rolling).

**Comment by jdkent** [comment]
email rainbo as well

**Comment by jdkent** [comment]
@TrevorLeeCline Template email for people: due monday

**Comment by TrevorLeeCline** [comment]
The following is a template email. Please let me know if anyone has any suggestions for better wording or to include something I have left out. 


Hello [name],

As a general reminder the uiowa BrainHack will be held July 23-24 from 8:30am to 5:00pm. 

Firstly, we would like to ask you if you will be available both Tuesday and Wednesday, or which day you will be available if not both. 

Secondly, as the goal of the BrainHack involves both teaching and learning, work-shopping current and upcoming projects, and connecting often separate fields of study for collaborative problem solving, we are asking you to put together a short (5 minute) presentation. This presentation should focus on something that you are now or soon will be working on, for which you hope to find innovative contributions. The presentation will be followed by a discussion of your project, so come ready for professional development.

University of Iowa, BrainHack

**Comment by jdkent** [comment]
Thank you Trevor for creating this template, looks great! Here are some suggestions:

> As a general reminder the uiowa BrainHack will be held July 23-24 from 8:30am to 5:00pm.

Some of the people we invite may not have registered for the brainhack yet. I might say something like:
"You are cordially invited to participate in the upcoming brainhack to be held July 23-24 from 8:30am to 5:00pm"

> Firstly, we would like to ask you if you will be available both Tuesday and Wednesday, or which day you will be available if not both.

LGTM (looks good to me)

> Secondly, as the goal of the BrainHack involves both teaching and learning, work-shopping current and upcoming projects, and connecting often separate fields of study for collaborative problem solving, we are asking you to put together a short (5 minute) presentation. This presentation should focus on something that you are now or soon will be working on, for which you hope to find innovative contributions. The presentation will be followed by a discussion of your project, so come ready for professional development.

I might move the question we are asking them closer to the beginning and split the first sentence.
"Secondly, we are asking you to put together a short (5 minute) presentation. This presentation should focus on something that you are now or soon will be working on, for which you hope to find innovative contributions. There will be a short  (1-3 minute) Q&A portion after your presentation. The goal of the BrainHack involves both teaching and learning, work-shopping current and upcoming projects, and connecting often separate fields of study for collaborative problem solving, so keep a broad audience in mind when creating a presentation."

> University of Iowa, BrainHack

you may think about adding the word "committee" after "BrainHack" (I'm also guilty of not doing this). That makes us sound a little more like people than a faceless event.

**Comment by jdkent** [comment]
cc @mpipoly, @GHarmata, @hjmjohnson for suggestions, we want to send out by the end of the day, so any edit suggestions should occur by **2:00pm**

**Comment by GHarmata** [comment]
How about this:

 <i>You are cordially invited to participate in the upcoming UIowa Brainhack to be held July 23-24 from 8:30am to 5:00pm.  The goal of this event is to provide introductions to data science and data science-related problems, to foster interdisciplinary collaboration, and allow people from different backgrounds to work together to solve real neuroscience-related data questions.  
 
If you decide to attend, we would be honored if you would put together a short (5 minute) presentation focusing on something that you are currently or will soon be working on, for which you hope to find innovative contributions. There will be a short (1-3 minute) Q&A portion after your presentation. The goal of the BrainHack involves both teaching and learning, work-shopping current and upcoming projects, and connecting often separate fields of study for collaborative problem solving, so keep a broad audience in mind when creating a presentation.

We would ask that you attend as much of the workshop as possible on one or both days, to give opportunities for others and yourself to ask questions, network, and potentially address your lab’s data science questions.  

Hope to see you there!  

Sincerely, 
The University of Iowa BrainHack Committee</i>

**Comment by TrevorLeeCline** [comment]
Edits look wonderful, thank you for contributing to the template design. Especially thanks for compiling the edits @GHarmata

**Comment by mpipoly** [comment]
I think this looks great. I have nothing to contribute. Great work guys!!!!

**Comment by jdkent** [comment]
I've sent out the emails, but I only got a couple replies. I think we have about enough projects to sustain a proper brainhack, I can pull up projects I'm working on to supplement the existing ones.

**Comment by mpipoly** [comment]
James - I know Joel has mentioned to me having trouble working with normally generated NIFTI-2 data and pushing it into CIFTI space. This might be a topic we can use with the goal of replicating some HCP style analyses with their tools in CIFTI space (where surface and subcortical volume information is store --among other things). I believe the package "CIFTIFY" for python can do this already but with some issues. --Just a thought?
