### ISSUE TITLE
Create Post Brainhack Survey

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#31]
Have participants give feedback on the event to improve for next year.

**Comment by jdkent** [comment]
[here is the start of the post brainhack survey](https://uiowa.ca1.qualtrics.com/jfe/preview/SV_a045I4rgNTpnsSp?Q_SurveyVersionID=current&Q_CHL=preview)

@mpipoly Could you help integrate some of the great questions you posed in your email (I think I already have you as a collaborator on this project)?
Specifically these ones:
>-What kinds of tutorials did you think helped you the most during this event?
          -Did you find Python and R tutorials to be highly useful? 
          -Could we have spent more time working on this?
\
-What kind of information did we provide that you found the most helpful?
          -Our schedule layout, Slack Page, solicitation (posters) ect..
\
-What do you think we could have done better?
           -Food, resource accessibility, layout of the day
\
-Were there things you feel we were not clear on? (ask about logistics, how to delegate in groups, asses group interest and strengths, outlining how a group might conduct their work/problem solving). 
           -Provide a formula/template for how a BrainHack team might structure themselves successfully
           -In opening remarks address questions and remind folks of the days events

If @GHarmata and @TrevorLeeCline could sign in the [qualtrics website](https://its.uiowa.edu/qualtrics) I can add you as collaborators to the project.

**Comment by mpipoly** [comment]
Before I forget... I want to also add questions on how folks rated their experience working with their group? Did they feel they were a team member or were they ignored? Did they choose to work alone?

-Sorry to dump alot of these questions... Would someone be willing to create a decision tree of questions centered on whether participants participated in a group or not and if they felt this worked well for them at BrainHack 2019? @GHarmata @TrevorLeeCline

**Comment by jdkent** [comment]
I will chime in, not trying to veto all this valuable information, but I am worried if anyone will take the time to fill a lot of free-form text entries (with my main worry of them being discouraged to fill out the survey at all). From the neuroimaging workgroup survey, about a third of the people filled it out, and it was a short 4-5 question survey. 

With that said, we could have a section for more extended questions for people to optionally fill out if they want to take the time to help us improve the event. That way we get the short easy answers, and optionally more information if the survey taker is kind with their time.

I can dedicate a little more time for adding questions and logic, but I do not know if I will be able to finish implementing the survey.

**Comment by mpipoly** [comment]
Hi James,

I am happy to help... I just have not used qualtrics before. A lot of these I figure would be if this, then.... style responses. I wanted to time myself completing the survey depending on choice before sending it out.

I think 5-10 minutes is ok for survey time? We can also put that in the email to encourage finishing it because people will know upfront that the time is 5-10 minutes.

Thoughts?


Marco A. Pipoly, B.S.
NSF Graduate Research Fellow
Graduate Student, PhD in Neuroscience
University of Iowa
marco-pipoly@uiowa.edu







________________________________

**Comment by jdkent** [comment]
Draft email:

Hello All,

You are receiving this email because you registered for the 2019 brainhack. **REGARDLESS** of attendance, we want to know how we can improve the overall execution of this event and we need **YOUR** help to do that. This survey takes only  **~4 MINUTES** of your time which will help us make our 2020 brainhack an event you want to brag to your friends about (professionally).

LINK TO SURVEY

Yours Truly,
The Brainhack Committee
james-kent@uiowa.edu
marco-pipoly@uiowa.edu
trevor-cline@uiowa.edu
gail-harmata@uiowa.edu
hans-johnson@uiowa.edu

**Comment by jdkent** [comment]
@GHarmata Thoughts on the email draft for sending out the survey link? We will send the email out on Thursday morning (~9:00am).

**Comment by jdkent** [comment]
Here are the survey results, great feedback to improve on for next year. [survey results](https://github.com/brainhack-uiowa/2019-brainhack/files/3521495/Default.Report.pdf).

**Comment by mpipoly** [comment]
@jdkent I looked over the feedback and in general, it isn't bad. Half of the group responded which is good. Did we want to have a debrief about this in the coming months or?

**Comment by jdkent** [comment]
I think we are done with meetings for this season, we begin to think about next year's brainhack next semester, probably when I'm done with the brain bee, mid-late February. We can recruit members for the committee before that time, however.
