### ISSUE TITLE
Make/Distribute Posters

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#6]
[The poster used last year for reference](https://docs.google.com/presentation/d/1LkdDwYoDdXnl0ZLZstZ8iZSVdS6LOkIIs3S77cAZYiQ/edit?usp=sharing), modify for this year, open to any design suggestions/changes

**Comment by jdkent** [comment]
Hans has a printer, Gail will provide a draft of the poster.

**Comment by GHarmata** [comment]
![Artboard 1](https://user-images.githubusercontent.com/11305962/57659010-61f55600-75a6-11e9-81db-b5e6eefd7234.png)

Thoughts?

**Comment by GHarmata** [comment]
I was also thinking of putting a QR code for the registration link.

**Comment by jdkent** [comment]
I like it aesthetically, great work :100:! However, there may be too much non-white space to satisfy the printing constraints. I'll let @hjmjohnson be the final word on that front.

**Comment by jdkent** [comment]
Pinging @hjmjohnson to see if this poster is okay to print.

**Comment by hjmjohnson** [comment]
@jdkent Fine. Do you want 20 copies made?

**Comment by jdkent** [comment]
We still need to add the registration link, but once that is added we can begin printing.

**Comment by jdkent** [comment]
@GHarmata here is the registration link: http://bit.ly/uibrainhack

Once that is added we can print the posters.

**Comment by jdkent** [comment]
pinging @GHarmata

**Comment by GHarmata** [comment]
[Brainhack poster.pdf](https://github.com/brainhack-uiowa/2019-brainhack/files/3262890/Brainhack.poster.pdf)

**Comment by GHarmata** [comment]
I
[Brainhack poster.pdf](https://github.com/brainhack-uiowa/2019-brainhack/files/3262937/Brainhack.poster.pdf)

**Comment by jdkent** [comment]
@hjmjohnson we are ready to print these, 20 copies sounds good. Thanks!

**Comment by jdkent** [comment]
pinging @hjmjohnson

**Comment by hjmjohnson** [comment]
Done!  They are printing right now.  They will be in my office.  I am traveling on campus a lot to different labs this week.  Please let me know when it is convenient to pick them up.

**Comment by jdkent** [comment]
Thanks Hans!

@TrevorLeeCline, I'm going to assign you to pick up and distribute posters. We will be meeting in person in 40 minutes, so we will determine a good time to pick up the posters then and I'll update this thread with that information.

**Comment by jdkent** [comment]
@hjmjohnson 
Trevor says he will be willing to pick them up after our meeting ends at 2:00pm, should that work or would another time be better?

**Comment by hjmjohnson** [comment]
That time works.

**Comment by jdkent** [comment]
posters out and about :100:
