### ISSUE TITLE
Groups To Contact for Advertisement/Advertisement Venues

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#7]
related to #1 and brainhack-uiowa/uiowaBIDS#7

- advertise to:
    - Psychology (psy-dept@list.uiowa.edu through becky-huber@uiowa.edu)
    - IIBI (hans-johnson@uiowa.edu)
    - INI (meghan-lawler@uiowa.edu)
    - Psychiatry (jatin-vaidya@uiowa.edu)
    - Computational Psychiatry (jacob-michaelson@uiowa.edu)
    - Neuroscience (megan-meyer@uiowa.edu)
    - Informatics (andrea-flaherty@uiowa.edu)
    - Graduate Women in Science (rachel-cole@uiowa.edu)
    - Biomedical Engineering (bme@engineering.uiowa.edu)
    - Computer Science (sriram-pemmaraju@uiowa.edu)
    - Electrical Engineering (ece@engineering.uiowa.edu)
- keep up facebook and twitter presence (alejandra-gomez@uiowa.edu)

**Comment by jdkent** [comment]
I also made [an event](https://events.uiowa.edu/28649) on the uiowa site.

**Comment by mpipoly** [comment]
Awesome jdkent! Have all of these organizations been contacted already?

**Comment by jdkent** [comment]
We've contacted Psychology, IIBI, INI, Computational Psychiatry, Neuroscience, and Informatics, 

We could still use a plug from 
- [x] Social Media (which honestly I could do)
- [x] Computer Science
- [x] GWIS

**Comment by jdkent** [comment]
- Jess Fiedorowicz: (get email)

**Comment by jdkent** [comment]
~@GHarmata contact Katrina about GWIS~

done

**Comment by jdkent** [comment]
Never contacted Jess Fiedorowicz

**Comment by kerry-tarrant** [comment]
mathbio@list.uiowa.edu,
math-graduate@list.uiowa.edu,
mathbiojournalclub@team.uiowa.edu
