### ISSUE TITLE
How to Handle Registration?

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#8]
from brainhack-uiowa/uiowaBIDS#7

## Registration 
- add a fee (and then add a scholarship if the registrants submits a project proposal)
- ask what the registrants would like to learn about/do
- ask registrants for sandwich/food order
- ask registrants to give a tutorial

**Comment by jdkent** [comment]
maybe use [signup genius](https://www.signupgenius.com/) for registration, or qualtrics with Andrea?

**Comment by jdkent** [comment]
emphasize how to think about data, and use tools for the data.

**Comment by jdkent** [comment]
treating this as a professional training experience, to motivate the event, to make this time commitment.

**Comment by jdkent** [comment]
I have a [draft of the registration form up](https://uiowa.ca1.qualtrics.com/jfe/preview/SV_3JlvEwdpnyEE8GV?Q_SurveyVersionID=current&Q_CHL=preview), @mpipoly could you take a look at it? (but anyone's feedback is desired)

**Comment by mpipoly** [comment]
Hi James,


I have some thoughts about the opening page. They are very minor though.


For Example:

The brainhack (and the training leading up to it) will serve as a professional development experience enhancing your ability to communicate with individuals from different backgrounds to collaboratively problem solve.


I feel that the word "product" sounds dissuasive as it creates an impression that their is an expectation for something polished.


A few other places I felt could use some word massaging as well but overall it looks really awesome. I was very impressed!


Best,


Marco A. Pipoly, B.S.
NSF Graduate Research Fellow
Graduate Student, PhD in Neuroscience
University of Iowa
marco-pipoly@uiowa.edu







________________________________

**Comment by jdkent** [comment]
Thank you for your patience, I've [updated the draft](https://uiowa.ca1.qualtrics.com/jfe/preview/SV_3JlvEwdpnyEE8GV?Q_SurveyVersionID=current&Q_CHL=preview), we will begin sending it out by the end of the week, please let me know if there are other edits you would like to suggest.

**Comment by jdkent** [comment]
Apparently you can invite others to collaborate on a qualtrics survey, in hindsight this ability should be obvious, but I didn't think of it until the work has been completed, for future brainhacks using qualtrics, collaborate!
