### ISSUE TITLE
Make Website

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2019-brainhack#9]
Like the [one last year](https://brainhack-uiowa.github.io/uiowa2018brainhack.github.io/), but maybe better?

**Comment by jdkent** [comment]
This will be the one-stop shop to see information about pre-training, registration, and the event proper

**Comment by mpipoly** [comment]
Is this fully realized in anyway?

**Comment by jdkent** [comment]
I think I'm just treating the qualtrics site as the main landing page for learning about the event. If someone wants to take this on and create a website (could be wordpress based, or whatever the university has to offer) I'm all for it, but I do not currently have the bandwidth to accomplish this task.

I'll put this on the agenda for the next meeting.

**Comment by jdkent** [comment]
check to see if the qualtrics html can be exported.

**Comment by jdkent** [comment]
Could not get this done in time.
